apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-uid2-load-test
spec:
  parallelism: 3
  arguments: --out experimental-prometheus-rw --tag replacecomment
  script:
    configMap:
      name: operator-stress-test
      file: replaced
  runner:
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "http://prometheus-kube-prometheus-prometheus.svc.cluster.local:9090/api/v1/write"
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "true"