package suite.core;

import common.HttpClient;
import common.KmsHelper;
import app.component.Core;
import com.fasterxml.jackson.databind.JsonNode;
import com.uid2.shared.Const;
import com.uid2.shared.attest.JwtService;
import io.vertx.core.json.JsonObject;
import org.junit.jupiter.api.condition.EnabledIf;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

@EnabledIf("common.EnabledCondition#isLocal")
public class CoreTest {
    @ParameterizedTest(name = "/attest - {0}")
    @MethodSource({
            "suite.core.TestData#baseArgs"
    })
    public void testAttest_EmptyAttestationRequest(Core core) {
        HttpClient.HttpException exception = assertThrows(
                HttpClient.HttpException.class,
                () -> core.attest("")
        );

        String coreUrl = core.getBaseUrl();

        assertEquals("Unsuccessful POST request - URL: " + coreUrl + "/attest - Code: 400 Bad Request - Response body: {\"status\":\"no attestation_request attached\"}", exception.getMessage());
    }

    /**
     * Tests valid attestation request with JWT signing.
     * 
     * LocalStack 4.x supports KMS Sign operation for RSA keys, so JWTs are generated.
     * 
     * Since LocalStack generates its own RSA key material,
     * we dynamically fetch the public key from LocalStack's
     * KMS using GetPublicKey API to validate JWT signatures.
     */
    @ParameterizedTest(name = "/attest - {0}")
    @MethodSource({
            "suite.core.TestData#baseArgs"
    })
    public void testAttest_ValidAttestationRequest(Core core) throws Exception {
        final String validTrustedAttestationRequest = "{\"attestation_request\":\"AA==\",\"public_key\":\"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl7kXK1wf15V9HgkQhbMK2nfJGbudmdXNrX7MZjFm07z6eEjaQsuqMteQumLRwn+RxEcXKVaxBAE3RQTFL9XsZc2OtRKOU+oMIQep8tmPFMgh83BzjLs5O5HZf510geFJO6qRqc3UHJT3ACxE7IkmRx1JIKFKPzTrthHdb2+D7bdJBPsVbwk7y+a36f5jvELGGzMC89LAvd7JpOmGsCAj6jwiEAKmmLId9bfe0YeLuebl95VfSzrQVdz82oGGQKXuJgKZtc/Xp1omZ9spm+zzVFJzsimxDdGdnaWMnas43VoTE04JDt+pucJTTbftIvu05frwkbZh3sQ2yBu5gBP7YwIDAQAB\",\"application_name\":\"uid2-operator\",\"application_version\":\"5.27.10-3f25586306\",\"components\":{\"uid2-attestation-api\":\"2.0.0-f968aec0e3\",\"uid2-shared\":\"7.2.4-SNAPSHOT\"}}";

        JsonNode response = core.attest(validTrustedAttestationRequest);

        assertAll("Attestation response should be successful",
                () -> assertNotNull(response.get("status")),
                () -> assertEquals("success", response.get("status").asText()));

        JsonNode body = response.get("body");
        assertAll("testAttest_ValidAttestationRequest - not-null body",
                () -> assertNotNull(body),
                () -> assertNotNull(body.get("attestation_token")),
                () -> assertNotNull(body.get("expiresAt")));

        // Verify JWTs are generated - LocalStack 4.x supports KMS Sign
        JsonNode jwtOptoutNode = body.get("attestation_jwt_optout");
        JsonNode jwtCoreNode = body.get("attestation_jwt_core");
        
        assertAll("JWTs should be generated by KMS Sign",
                () -> assertNotNull(jwtOptoutNode, "attestation_jwt_optout should not be null"),
                () -> assertFalse(jwtOptoutNode.isNull(), "attestation_jwt_optout should not be JSON null"),
                () -> assertFalse(jwtOptoutNode.asText().isEmpty(), "attestation_jwt_optout should not be empty"),
                () -> assertNotNull(jwtCoreNode, "attestation_jwt_core should not be null"),
                () -> assertFalse(jwtCoreNode.isNull(), "attestation_jwt_core should not be JSON null"),
                () -> assertFalse(jwtCoreNode.asText().isEmpty(), "attestation_jwt_core should not be empty"));

        // Verify JWT format (header.payload.signature)
        String jwtOptout = jwtOptoutNode.asText();
        String jwtCore = jwtCoreNode.asText();
        assertAll("JWTs should have valid format",
                () -> assertEquals(3, jwtOptout.split("\\.").length, "OptOut JWT should have 3 parts"),
                () -> assertEquals(3, jwtCore.split("\\.").length, "Core JWT should have 3 parts"));

        // Fetch the public key dynamically from LocalStack KMS and validate JWT signatures
        String publicKeyBase64 = KmsHelper.getPublicKeyFromLocalstack();
        JsonObject config = new JsonObject()
                .put(Const.Config.AwsKmsJwtSigningPublicKeysProp, publicKeyBase64);
        JwtService jwtService = new JwtService(config);
        
        // Validate optout JWT signature
        var optoutValidation = jwtService.validateJwt(jwtOptout, Core.OPTOUT_URL, Core.CORE_URL);
        assertTrue(optoutValidation.getIsValid(), "OptOut JWT signature should be valid");
        
        // Validate core JWT signature  
        var coreValidation = jwtService.validateJwt(jwtCore, Core.CORE_URL, Core.CORE_URL);
        assertTrue(coreValidation.getIsValid(), "Core JWT signature should be valid");

        String optoutUrl = body.get("optout_url").asText();
        assertAll("testAttest_ValidAttestationRequest OptOut URL not null",
                () -> assertNotNull(optoutUrl),
                () -> assertEquals(Core.OPTOUT_URL, optoutUrl));
    }

    @ParameterizedTest(name = "/operator/config - {0}")
    @MethodSource({
            "suite.core.TestData#baseArgs"
    })
    public void testOpertorConfig_ValidRequest(Core core) throws Exception {
        JsonNode response = core.getOperatorConfig();

        assertAll("testOpertorConfig_ValidRequest has valid response",
                () -> assertNotNull(response),
                () -> assertInstanceOf(Integer.class, response.get("version").asInt()),
                () -> {
                    JsonNode runtimeConfig = response.get("runtime_config");
                    assertNotNull(runtimeConfig, "runtime_config should not be null");
                }
        );
    }
}
