name: Release UID2 E2E Image
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish Pre-release' || format('Release {0}', inputs.release_type)}} Docker Image by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: The type of release
        options:
          - Snapshot
          - Patch
          - Minor
          - Major
      version_number_input:
        description: If set, the version number will not be incremented and the given number will be used.
        type: string
        default: ''
      vulnerability_severity:
        description: The severity to fail the workflow if such vulnerability is detected. DO NOT override it unless a Jira ticket is raised.
        type: choice
        options:
          - CRITICAL,HIGH
          - CRITICAL,HIGH,MEDIUM
          - CRITICAL (DO NOT use if JIRA ticket not raised)

jobs:
  Image:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-java-to-docker-versioned.yaml@kcc-fix-snapshot-release
    with:
      release_type: ${{ inputs.release_type }}
      version_number_input: ${{ inputs.version_number_input }}
      vulnerability_severity: ${{ inputs.vulnerability_severity }}
      java_version: 21
      skip_tests: true
    secrets: inherit
