name: Publish E2E Test Suites
run-name: ${{ format('Publish E2E Test Suites{0} {1} Release', ':', inputs.release_type) }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
          - Snapshot
          - Patch
          - Minor
          - Major
      version_number_input:
        description: If set, the version number will not be incremented and the given number will be used.
        type: string
        default: ''

jobs:
  Image:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-docker-versioned.yaml@v3
    with:
      release_type: ${{ inputs.release_type }}
      version_number_input: ${{ inputs.version_number_input }}
      java_version: '21'
      force_release: 'yes'
      skip_tests: true
    secrets: inherit
