name: Validate Docker Image
on:
  workflow_dispatch:
    inputs:
      failure_severity:
        description: 'Must be one of CRITICAL, HIGH, MEDIUM'
        required: false
        default: 'HIGH'
      fail_on_error:
        description: 'If true, will fail the build if vulnerabilities are found'
        required: true
        type: boolean
        default: true
  schedule:
    - cron: '0 20 * * *' #every day at 20:00

jobs:
  build-publish-docker-default:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-validate-image.yaml@v2.3.6
    with: 
      failure_severity: ${{ inputs.failure_severity || 'HIGH'}}
      fail_on_error: ${{ inputs.fail_on_error || true }}
      java_version: '21'
      skip_tests: true
    secrets: inherit
